.TH NDISGTK 8 "2007-05-13" "0.7" "Ndiswrapper driver installation tool"

.SH NAME
ndisgtk \- load Windows wireless drivers with ndiswrapper

.SH SYNOPSIS
.B ndisgtk

.SH DESCRIPTION
.B ndisgtk
is a program for installing Windows wireless drivers from a graphical user interface.

.SH OPTIONS
.B ndisgtk
has no options.

.SH AUTHOR
ndisgtk was written by Sam Pohlenz <retrix@internode.on.net>.
It is now developed by Julian Andres Klode <jak@jak-linux.org>
.PP
This manual page was written by Julian Andres Klode <jak@jak-linux.org> based on
and older ndisgtk manpage by Sam Pohlenz <retrix@internode.on.net>.
